keys:
  - &admin:
    - &master age13krpm9nls3799yaw3tl83rcmpykc75fxt7v48rvevx3ta5v42ayqsk5umc
  - &users
    - &merrinx age1rn9ttgtglurwksgfgary4v5t8qqeqqqack4g2v7qge4z7z97meyq4w8hmq
    - &gamebox age1zl3kjad6jzppfd8ksnf5377mfnqdfmrqk9sl7ju0x0dlw4szscsqml503s
  - &hosts:
    - &terangreal age160ts305y3y3w899tvtccladc4ylvzfr6xcc7mq0re0h28t2qacksajh76m
    - &tuathaan age1w0axgtcwyectqp0jkn5u8ujsxkr0uan559xcpujq9wdrfzwtvdhs7nsj8n
    - &tanchico age1azldnluhrefkfnt0cl63met4mhpnhtyg07ms9yc4ajwdqc7zqqzsz45tpr

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *master
          - *merrinx
          - *gamebox
          - *terangreal
          - *tuathaan
          - *tanchico

