name: "Pull Request Checker"

on:
  pull_request: {}

jobs:
  generate_matrix:
    runs-on: ubuntu-24.04
    outputs:
      checks: ${{ steps.gen_checks.outputs.checks }}
      packages: ${{ steps.gen_packages.outputs.packages }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          token: "${{ secrets.TEST_TOKEN }}"
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.TEST_TOKEN }}
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://merrinx.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= merrinx.cachix.org-1:xxPuUGRPdYkH1eAUy1hLXt9w3GCfKTFVrkiWdlPEN9E= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc=
          install_url: https://releases.nixos.org/nix/nix-2.32.5/install
      - name: Generate flake.json
        run: nix flake show --json > flake.json
      - id: gen_packages
        run: |
          packages=$(jq -c '.packages."x86_64-linux" | keys' < flake.json)
          echo "packages=$packages" >> "$GITHUB_OUTPUT"
      - id: gen_checks
        run: |
          checks=$(jq -c '.checks."x86_64-linux" | keys' < flake.json)
          echo "checks=$checks" >> "$GITHUB_OUTPUT"

  build_checks:
    runs-on: ubuntu-24.04
    needs: [generate_matrix]
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        check: ${{ fromJson(needs.generate_matrix.outputs.checks) }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          token: "${{ secrets.TEST_TOKEN }}"
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.TEST_TOKEN }}
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://merrinx.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= merrinx.cachix.org-1:xxPuUGRPdYkH1eAUy1hLXt9w3GCfKTFVrkiWdlPEN9E= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc=
          install_url: https://releases.nixos.org/nix/nix-2.32.5/install
      - name: Set up cachix
        uses: cachix/cachix-action@v17
        with:
          name: merrinx
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true
      - name: Build the check
        run: nix build .#checks.x86_64-linux.${{ matrix.check }} --no-link

  build_flake:
    runs-on: ubuntu-24.04
    needs: [generate_matrix]
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        package: ${{ fromJson(needs.generate_matrix.outputs.packages) }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          token: "${{ secrets.TEST_TOKEN }}"
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.TEST_TOKEN }}
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://merrinx.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= merrinx.cachix.org-1:xxPuUGRPdYkH1eAUy1hLXt9w3GCfKTFVrkiWdlPEN9E= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc=
          install_url: https://releases.nixos.org/nix/nix-2.32.5/install
      - name: Set up cachix
        uses: cachix/cachix-action@v17
        with:
          name: merrinx
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pathsToPush: result
      - name: Build the package
        run: nix build .#${{ matrix.package }} --out-link result

  check_flake:
    runs-on: ubuntu-24.04
    needs: [generate_matrix]
    continue-on-error: true
    steps:
      - name: Clean up root space and mount /nix on /mnt
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo rm -rf /opt/hostedtoolcache /opt/microsoft
          sudo rm -rf /usr/local/share/boost /usr/local/.ghcup
          sudo rm -rf /usr/share/swift /usr/local/graalvm
          sudo apt-get clean

          sudo mkdir -p /nix
          sudo mkdir -p /mnt/nix
          sudo mount --bind /mnt/nix /nix
          sudo chown -R runner:runner /nix

          df -h
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          token: "${{ secrets.TEST_TOKEN }}"
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.TEST_TOKEN }}
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://merrinx.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= merrinx.cachix.org-1:xxPuUGRPdYkH1eAUy1hLXt9w3GCfKTFVrkiWdlPEN9E= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc=
          install_url: https://releases.nixos.org/nix/nix-2.32.5/install
      - name: Set up cachix
        uses: cachix/cachix-action@v17
        with:
          name: merrinx
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true
      - name: Run generic check
        run: nix flake check --keep-going
