email-user: ENC[AES256_GCM,data:cbhfgavYIwQeqoSY3q9RcBU=,iv:om3rvnh2Rx3N7p4XLSyt4Ei97hVctteY+6bCulhtydE=,tag:Quc0wZIcW3usDp10yYtbyA==,type:str]
email-passwd: ENC[AES256_GCM,data:DFDRhWkTg26bbr155eGv8lRXO1nrBg==,iv:bXvPEvdi9zm8ug7t3qsrtxx4iLFAW71X4TK+eVwXYqs=,tag:s8/xtbk5+4bMCMRntI0eQA==,type:str]
email-alias-private: ENC[AES256_GCM,data:z6z3bbsCbwoV2WFTGihMU+zHd3453YNg7A==,iv:FIqCw9L+5HZoeM77kWQPDpbxrY8/7cZAHam7pE2WS6I=,tag:09G6yLyQgeLfgg3KJDOI/g==,type:str]
email-alias-service: ENC[AES256_GCM,data:NXqvY5axKkphkYT/jjAqCbU+gkss3PprXCoQbR45,iv:FiBhvULPawD0Rg5QTYNjn+x0+k514s8dfRbJaGv4/Jw=,tag:dUykIyLZ8fu98US5f+1mJQ==,type:str]
email-alias-social: ENC[AES256_GCM,data:zszRar01pdee+bYH6h6VRttWPrlyoL62DYnqg74i,iv:5mftjBg5cplrW2hgPRxujt+yyuS8CR+eXolm64K4D/w=,tag:iZP1tExQOZcuQutbKDlqYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13krpm9nls3799yaw3tl83rcmpykc75fxt7v48rvevx3ta5v42ayqsk5umc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Zjc4djZDbm5wdUNjYWc5
            MHNHRmtiY09WbUNIUWtqVG1OT2dxaDNxVUhBCnR2V1lpNWd0cGpuZkdWWEYyTGdE
            K21BaDBDUGsvbnRCOEZWb01uYkZDRXcKLS0tIEN1VlBoSmVEQ0x1cnY0c2twcWxi
            OVltbkpoYStMMk8vODVQaVZ6bEI5WDAKBQG4fJfdg3NZK1XdJnqnTtFw5hR9WJte
            mKDqjK4YZ5RiH7tenNSkrTx8kUxxjSGx1mpVmb3v7TmIhUh0VeWg0Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yrlm5lvttp2awkp63gmkg4jeca9zfzxwkejyxpsv7t09cqxefpys7g4ylk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWk9wY2JqQkw3WHNZNEFp
            d2NMK3VRSGY5V0x0ZW1scVRQQlVrWEZUQlNVCjM0SFJrSXErTkZZdTByTnNyd24v
            bC9EeGJvTzZ2bENpTWF4cXJvaXFlbGMKLS0tIGpWcFR4cVZRUzZoN3ZTclNqMno2
            eWE1cllhNEh2YkhJNmpUTDU2cUdvN1kKkvGKjOqUtOWeKQHP9dlJHv8JIeD1VhVN
            gmh9Lc2ZHHe7Rf8IxiZJCz49gy1UPLtJIlaOgLb5S3ZNxsFfLfxNTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zspv49cc4dr0klgun0c7xvk0pmeqrh9k0024eepf7j47rayk9pcq08f52t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRGtOUkp6ZjVlUit3M2N3
            TGtoUDl5cGo4VnBBc3lPck5DaThveWJzeldBCmtjNm4rZE9pbTU1dk85bTh0WlY4
            bERiSFFGZW9vR1gvYndLVkUwc2RCSWsKLS0tIHZiR01lM3NZVUg5U1lMQXEyQ2RW
            TXRIeUZ4SElCR20xQ05KYlkzYTA0QU0KMYa6IwxFP5yzUB1yMXbmrsVkLOPDw6Kl
            7HJDyPbtgPEVxTn+Qcu1H31je2I30Z4VoGekgh7pPiwqaKu9APJXnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-05T23:49:20Z"
    mac: ENC[AES256_GCM,data:v/FNwf4VDlMfuZHASP9ZanhNc23GSukxg6RXMi8zd/ml6SwFhmyoVMLumJOLaIpX6eVH9SaV88j/3kPFRymukXZCIG6MogIwQMJ/eLp4gP/DC9eDL+ahVnqBdGaYSiA6B6rP/3MujkyZ+SC9VcpbZuGQZg5WDxrAN6R+GPYmrek=,iv:51Tvi4h+Zj+6RYrv1Jk+8ngHUjYFeWXRYM9TmiE8ZAw=,tag:0pdDRgoKCVXW+WkdPEpmbQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
