email-passwd: ENC[AES256_GCM,data:DFDRhWkTg26bbr155eGv8lRXO1nrBg==,iv:bXvPEvdi9zm8ug7t3qsrtxx4iLFAW71X4TK+eVwXYqs=,tag:s8/xtbk5+4bMCMRntI0eQA==,type:str]
email-user: ENC[AES256_GCM,data:cbhfgavYIwQeqoSY3q9RcBU=,iv:om3rvnh2Rx3N7p4XLSyt4Ei97hVctteY+6bCulhtydE=,tag:Quc0wZIcW3usDp10yYtbyA==,type:str]
email-alias-private: ENC[AES256_GCM,data:z6z3bbsCbwoV2WFTGihMU+zHd3453YNg7A==,iv:FIqCw9L+5HZoeM77kWQPDpbxrY8/7cZAHam7pE2WS6I=,tag:09G6yLyQgeLfgg3KJDOI/g==,type:str]
email-alias-service: ENC[AES256_GCM,data:NXqvY5axKkphkYT/jjAqCbU+gkss3PprXCoQbR45,iv:FiBhvULPawD0Rg5QTYNjn+x0+k514s8dfRbJaGv4/Jw=,tag:dUykIyLZ8fu98US5f+1mJQ==,type:str]
email-alias-social: ENC[AES256_GCM,data:zszRar01pdee+bYH6h6VRttWPrlyoL62DYnqg74i,iv:5mftjBg5cplrW2hgPRxujt+yyuS8CR+eXolm64K4D/w=,tag:iZP1tExQOZcuQutbKDlqYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13krpm9nls3799yaw3tl83rcmpykc75fxt7v48rvevx3ta5v42ayqsk5umc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORlZlaS9JeHAweGRPYTR3
            T1Z1bThKOG1oVVNPYXBCbUs1bW82aHVTTDBjCjNnbFpPU1YzczFZbmR6QXdmQkRu
            dVVKa2hWc0RLcDVjdWlFSmlJSlBYY28KLS0tIFJYRWlpbTRJdmRMa0JkZExEbEs4
            Q2t4N2xUN0N2ZUMrVHVmSWp4ZklQSzQKFHW1lXi3xqIvaA3ANZo4yMoCNux30+md
            5itBo9pG9FlEMnheGNZfHcg9BAYPOv/QIWSo5kBNrQ8IQlssF95Twg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yrlm5lvttp2awkp63gmkg4jeca9zfzxwkejyxpsv7t09cqxefpys7g4ylk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdUxISFNtVGQzV1c2d2tk
            Z1FBNGdadFE4YzA4VllwUkN1K1ZDNDUramtJClA4cjlZV215S0RVR1NpUDVFSEkr
            b25sQmRWd0lmQUpsbXcwaWpweTVyRjAKLS0tIGhhbkp3dnF4RzhwSzVwZlJNcjJr
            MDVqTGgzSldNMVJyRDdvNU1pL2k5dGsKJ2abaLqNe013b3ihik3hZK5l39fc1BUp
            PsCYr8zhXb7dIBwU25zBSbs0UYTpYVMS1TGGak6vwHlzQxSTek3GiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-05T19:18:20Z"
    mac: ENC[AES256_GCM,data:DmdoLS52pNocJyv/uNivdUwAv4frRLIWG/HjeM3JarQtj3WQhjOEgFCDv6EjTLkOqNBQzuE4I1tAI3fB/wrBloW8mCXnAwDY193DpHDOj4lhD5LefW4voYrSmxMWtlwY1mhOp8hMkOT9tPgbu/tpAGuKKxMvdDETGkhKS4RzRYk=,iv:2NINPVllmkK688sNuNpm7YbWbkmQi7ZSnGTIXroIpFw=,tag:UB9hwaW0Ub1CquycquLq4g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
