email-passwd: ENC[AES256_GCM,data:DFDRhWkTg26bbr155eGv8lRXO1nrBg==,iv:bXvPEvdi9zm8ug7t3qsrtxx4iLFAW71X4TK+eVwXYqs=,tag:s8/xtbk5+4bMCMRntI0eQA==,type:str]
email-user: ENC[AES256_GCM,data:cbhfgavYIwQeqoSY3q9RcBU=,iv:om3rvnh2Rx3N7p4XLSyt4Ei97hVctteY+6bCulhtydE=,tag:Quc0wZIcW3usDp10yYtbyA==,type:str]
email-alias-private: ENC[AES256_GCM,data:z6z3bbsCbwoV2WFTGihMU+zHd3453YNg7A==,iv:FIqCw9L+5HZoeM77kWQPDpbxrY8/7cZAHam7pE2WS6I=,tag:09G6yLyQgeLfgg3KJDOI/g==,type:str]
email-alias-service: ENC[AES256_GCM,data:NXqvY5axKkphkYT/jjAqCbU+gkss3PprXCoQbR45,iv:FiBhvULPawD0Rg5QTYNjn+x0+k514s8dfRbJaGv4/Jw=,tag:dUykIyLZ8fu98US5f+1mJQ==,type:str]
email-alias-social: ENC[AES256_GCM,data:zszRar01pdee+bYH6h6VRttWPrlyoL62DYnqg74i,iv:5mftjBg5cplrW2hgPRxujt+yyuS8CR+eXolm64K4D/w=,tag:iZP1tExQOZcuQutbKDlqYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13krpm9nls3799yaw3tl83rcmpykc75fxt7v48rvevx3ta5v42ayqsk5umc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRWxHYzhOVkhQNWgxU0Z5
            aEJPNFZ1aTVJcUlTOW1tYitxdGpaVjIyUEQ0CnZ3dzBNemZIb25WdVdtY2s4Zk12
            KzVNblRjMEVid1picFpoRUlRb2xPWUkKLS0tIGpySmZ3OEFVVHBweHF2TUlEdXB5
            SGp1VzVsaStBUkE1Zi9wcUFpV2tHb1EKPrQhExPSjCi64IF8ulKbv/gIot/0Qm1T
            Ljzzr3tV2cBeP4GVWixTpLMRqcNVIZ6lP1iMpzcOX1UsgbxFoXKelg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yrlm5lvttp2awkp63gmkg4jeca9zfzxwkejyxpsv7t09cqxefpys7g4ylk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcnJJNFpYWVE1aEdzUmcx
            UlRVNFdjVjlXQ2Q2RFRoQi8zL0o2V2pSRUZzCll5S0drSFNOM2Eza0xRZ1EyMVZN
            dG1pNDc0V01BTmF3WklSdHpvK1hIcDQKLS0tIHR2eWErcnUyZ2g3YXFPQ21xcUQz
            endaVEtKNDdqU25EalRmRVZuTkJPNVkK9I/bTfAJSHOSC4s4sDaKSjx6DMttMe8w
            zJleem3s2Tfh20n0oY+CiYNRn4HKYeqix1ZaVeM1lva4ByzgkCvSqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zspv49cc4dr0klgun0c7xvk0pmeqrh9k0024eepf7j47rayk9pcq08f52t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dS9Ea2hzaWJ0cE5pR1B2
            alBnNFgrZ1RESGpsNW1YZWZZMG9TSmVoOFdVCmgrM04zVHB3YjdkQUU1ZVRUZWNN
            WVRVbUJhV3Nub3pqTG52WExXOWZMaWsKLS0tIDZWNlI1d3JOMnFQUkxuUVBRQWla
            UXY0blNNR2phUFluQTF6MWRxUVFlaEkKvQNUQk/DB/NPz5nP+e/WC24Bx2YvfH8i
            v7Gh5rcpnwjaBtl8rvpbgU6bEQCzNPDvyS6xCqF3gx6FdWL45c0lXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-05T19:18:20Z"
    mac: ENC[AES256_GCM,data:DmdoLS52pNocJyv/uNivdUwAv4frRLIWG/HjeM3JarQtj3WQhjOEgFCDv6EjTLkOqNBQzuE4I1tAI3fB/wrBloW8mCXnAwDY193DpHDOj4lhD5LefW4voYrSmxMWtlwY1mhOp8hMkOT9tPgbu/tpAGuKKxMvdDETGkhKS4RzRYk=,iv:2NINPVllmkK688sNuNpm7YbWbkmQi7ZSnGTIXroIpFw=,tag:UB9hwaW0Ub1CquycquLq4g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
