email-user: ENC[AES256_GCM,data:cbhfgavYIwQeqoSY3q9RcBU=,iv:om3rvnh2Rx3N7p4XLSyt4Ei97hVctteY+6bCulhtydE=,tag:Quc0wZIcW3usDp10yYtbyA==,type:str]
email-master-passwd: ENC[AES256_GCM,data:k2kUmt73SiAFwrCrfKRv1vjRdnku8Q==,iv:sQXpFUBX+SqmP1NVdLVnrj2twWDUws8pOCjB1GyDLrA=,tag:X9QTGxYC8z5JZSXk2zMTaA==,type:str]
email-work-passwd: ENC[AES256_GCM,data:+pRGghL9e8HhzKhLdKlFxACg6uBqxg==,iv:kcSPQVGtU1vAEMU9ChHEEvsWP6M2jlKuisMH+t1EA44=,tag:fzbDIG3HoPilzXK0ta57zg==,type:str]
email-alias-private: ENC[AES256_GCM,data:z6z3bbsCbwoV2WFTGihMU+zHd3453YNg7A==,iv:FIqCw9L+5HZoeM77kWQPDpbxrY8/7cZAHam7pE2WS6I=,tag:09G6yLyQgeLfgg3KJDOI/g==,type:str]
email-alias-service: ENC[AES256_GCM,data:NXqvY5axKkphkYT/jjAqCbU+gkss3PprXCoQbR45,iv:FiBhvULPawD0Rg5QTYNjn+x0+k514s8dfRbJaGv4/Jw=,tag:dUykIyLZ8fu98US5f+1mJQ==,type:str]
email-alias-social: ENC[AES256_GCM,data:zszRar01pdee+bYH6h6VRttWPrlyoL62DYnqg74i,iv:5mftjBg5cplrW2hgPRxujt+yyuS8CR+eXolm64K4D/w=,tag:iZP1tExQOZcuQutbKDlqYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13krpm9nls3799yaw3tl83rcmpykc75fxt7v48rvevx3ta5v42ayqsk5umc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVnVYb0dQM1pnN3h5NUwz
            U3B0R3RYM3pqdWtXV0VSZEdKS3hEL2kxVmhjCi9zMmc1TENZNHZRM0tsT2w5bzRz
            dzZzbjNSdFdDR2JMcnE5QWJxYitRMlEKLS0tIHc2UU5MQXhSQ0VKNzV4d0VzYkhC
            b0xQakFQZm9OV0lrWFNKcW9vQnpBSUEKN+kbvEtvGzIuKfhD7OLswuggHipoqI31
            nrPGx3Jq0nn5zrXxByg16M4VaHSJGEfSetlonwQHHkep5+5KcyJ9CQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rn9ttgtglurwksgfgary4v5t8qqeqqqack4g2v7qge4z7z97meyq4w8hmq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRzYxenR5Tlk3ZVladGdW
            OUtEV2MzNVNpU0JTbGdXTERFZ3hoNW5kWm1VCkhTcThGM1U3b1JIOGlxS0VjLzh5
            TXFNazh3ZDZ2QjFmOGQzZUZqNTRvS28KLS0tIEhiWGhEdVROT0hDSmpZdUdwN0JI
            WDVkdmtZdG5CcUliMkFRcHM3TTVHaU0KQtK3z284+PvEJ+tbDhBXFHPTEezP4W/0
            drTczIN/aV1bbWVq/Tcl8qvHHjlJagLqAnK6FVf+2Et/qG2E6D7L5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yrlm5lvttp2awkp63gmkg4jeca9zfzxwkejyxpsv7t09cqxefpys7g4ylk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUjgzcFJWTkxyV0Jmbmtx
            MlRaa1BWUnZNWUVRNFdiUzFjWkwzWVRDeG40CkhjTExabXEyUmdSd3NiSmZ6L0hp
            SERVQTNORVNlaGFwalhWM2o1dktKWVEKLS0tIHNRalQ0QThUN0NWczljd0Z0MTg3
            UTk3dGZsUnYwamJqb0YrRFRkSlpmZGcKEfsfkwpna9oPrd6sAKgXORXu9B7OmJtf
            4EMclhKFDgMvvwrug/sKl+CBsqU4Xm57f/UlKTE7UOjHP9KNkRv/eA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zspv49cc4dr0klgun0c7xvk0pmeqrh9k0024eepf7j47rayk9pcq08f52t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhN3JuaHRFZUZnd0VJNTB6
            OEV2UWpveGZCSWtQUlBaUlhDVFZQQ2wrVWhZCndDKzhJUFNZTVluVUNUSWVCS2Fo
            TUM4bjdPdm5qUkdObGV1TG5zQ01Fa2MKLS0tIHVmai9CVUo3TCtiRTB1emJZWkpP
            M1ZzamFZSU5iYzFEYmtFQjhoSzU4MmMKSmMfEcAz18nZcdZeoGm5ksq5Q68fV8Y/
            C4wndesM03L37O4xUqOx7qJ8+urlI5gWuDW/ZpoXnbLlGvIJD/Gryg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-06T05:45:33Z"
    mac: ENC[AES256_GCM,data:iktfYzSv0SQAoI7pqbijUEAltY/i8mnu7tDALcqYhjn6TmhqRO6D9qAI2ySCzxceURU2JLUuzjJDoRYBFgzpTaVAb1E6z91D18h6/LnGoPAdPT/Ctp/jX9c1UfCKo4LJP7AnAFYy+bEGovnPBRRg5nwO5jHPu1TQrsjzPqKXvZc=,iv:gl3foWzEWwtUXVA8mas0QomCrKrkVFR0+sbdrfBwVEA=,tag:bR/t4TJ1dbsvOLqgQanxew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
