#!/usr/bin/env bash

# Get the art of the currently playing song in playerctl
art=$(playerctl metadata mpris:artUrl | sed 's/open.spotify.com/i.scdn.co/g')

if [[ -z "$art" ]]; then
    echo "No art"
else
    echo "$art"
fi
